#!/bin/bash
#SBATCH -p LM
#SBATCH --mem=2999GB
#SBATCH -t 72:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=markphuong@gmail.com

#echo commands to stdout

module unload python
module load python/2.7.11_gcc
module load samtools/1.3
module load picard/2.1.1
module load bowtie2/2.2.7
module load java/jdk8u73

#move to working directory
cd $LOCAL

cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/4blastagain/*_filtered_recipblast $LOCAL


cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/2mapping/*.vcf $LOCAL
cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/4blastagain/lophi* $LOCAL
cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/4blastagain/*.cov $LOCAL
cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/5filter/*.py $LOCAL
cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/4blastagain/*_mito_contigs.fasta $LOCAL
cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/4blastagain/mapfile $LOCAL

python remove_overlappers.py
python get_alternative_alleles.py
python filter_coverage_het.py


cp * /pylon5/bi4s86p/phuong/nico.turridae/mitodna/5filter/results/
