#!/bin/bash
#SBATCH -p LM
#SBATCH --mem=576GB
#SBATCH -t 72:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=markphuong@gmail.com

#echo commands to stdout

module unload python
module load python/2.7.11_gcc
module load samtools/1.3
module load picard/2.1.1
module load bowtie2/2.2.7
module load java/jdk8u73

#move to working directory
cd $LOCAL

cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/1blasting/*phylo_contigs.fa $LOCAL
cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/2mapping/*.vcf $LOCAL

cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/3getcov/*.py $LOCAL
cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/2mapping/mapfile $LOCAL





#run python script
python cov_het_Wrapper.py --map mapfile

cp * /pylon5/bi4s86p/phuong/nico.turridae/mitodna/3getcov

