#!/bin/bash
#SBATCH -p LM
#SBATCH --mem=2880GB
#SBATCH -t 72:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=markphuong@gmail.com

#echo commands to stdout

module load python/2.7.11_gcc
module load samtools/1.3
module load picard/2.1.1
module load bowtie2/2.2.7
module load java/jdk8u73

#move to working directory
cd $LOCAL

cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/2mapping/mapfile $LOCAL
cp /pylon5/bi4s86p/phuong/nico.turridae/mitodna/2mapping/mapping.py $LOCAL



#run python script
python mapping.py --map mapfile
